version: "3.6"
services:
    liked:
        image: likechain/likechain
        container_name: likechain_liked
        volumes:
            - ./.liked:/root/.liked
            - ./.likecli:/root/.likecli
        ports:
            - 26656:26656
            - 26657:26657
        restart: always
        command: ["liked", "--get-ip", "start"]
networks:
    default:
        name: likechain