version: "3.6"
services:
  api:
    image: likechain/golang
    container_name: likechain_api
    volumes:
      - ./abci:/go/src/github.com/likecoin/likechain/abci
    ports:
      - 3000:3000
    environment:
      GO111MODULE: "on"
      LIKECHAIN_API_CLIENT_HOST: tendermint-1:26657
    command: ["go", "run", "abci/cmd/api/main.go"]
  abci-1: &abci-node
    image: likechain/golang
    container_name: likechain_abci-1
    volumes:
      - ./abci:/go/src/github.com/likecoin/likechain/abci
    environment:
      GO111MODULE: "on"
    command: ["go", "run", "abci/cmd/abci/main.go"]
  tendermint-1: &tendermint-node
    image: likechain/tendermint
    container_name: likechain_tendermint-1
    hostname: tendermint-1
    depends_on:
      - abci-1
    volumes:
      - ./tendermint/nodes/1:/tendermint
    ports:
      - 26656:26656
      - 26657:26657
    entrypoint: tendermint node --moniker=`hostname` --p2p.persistent_peers=""
    command:
      - --proxy_app=tcp://abci-1:26658
