version: "3.6"
services:
  api:
    image: likechain/abci
    container_name: likechain_api
    volumes:
      - ./abci:/go/src/github.com/likecoin/likechain/abci
      - /go/src/github.com/likecoin/likechain/api/vendor
    ports:
      - 3000:3000
    environment:
      - LIKECHAIN_API_CLIENT_HOST=tendermint-1:26657
    command: ["go", "run", "cmd/api/main.go"]
  abci-1: &abci-node
    image: likechain/abci
    container_name: likechain_abci-1
    volumes:
      - ./abci:/go/src/github.com/likecoin/likechain/abci
      - /go/src/github.com/likecoin/likechain/abci/vendor
  tendermint-1: &tendermint-node
    image: likechain/tendermint
    container_name: likechain_tendermint-1
    hostname: tendermint-1
    depends_on:
      - abci-1
    volumes:
      - ./tendermint/nodes/1:/tendermint
    ports:
      - 26657:26657
    entrypoint: tendermint node --consensus.create_empty_blocks=false --moniker=`hostname` --p2p.persistent_peers=""
    command:
      - --proxy_app=tcp://abci-1:26658

  # Auto-generated configs
